# Generated by Django 4.0.4 on 2022-05-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='division',
        ),
        migrations.AddField(
            model_name='member',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.division'),
        ),
    ]
