# Generated by Django 4.0.4 on 2022-05-20 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_accepted_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accept',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Accepted',
        ),
    ]
